<?php
// Url rewrite
// https://www.yourinspirationweb.com/2010/06/10/il-mod_rewrite-e-la-magia-di-riscrivere-gli-url/
// https://www.ibenic.com/custom-wordpress-rewrite-rule-combine-taxonomy-post-type/

// Adds a rewrite rule that transforms a URL structure to a set of query vars.
// Any value in the $after parameter that isn't 'bottom' will result in the rule
// being placed at the top of the rewrite rules.
// @since 0.0.1
// @global WS_Rewrite $ws_rewrite WordPress Rewrite Component.
// @param string       $regex Regular expression to match request against.
// @param string|array $query The corresponding query vars for this rewrite rule.
// @param string       $after Optional. Priority of the new rule. Accepts 'top' or 'bottom'. Default 'bottom'.

function add_rewrite_rule( $regex, $query, $after = 'bottom' ) {
	global $ws_rewrite;
	$ws_rewrite->add_rule( $regex, $query, $after );
}

// Remove rewrite rules and then recreate rewrite rules.
// @since 0.0.1
// @global WS_Rewrite $ws_rewrite
// @param bool $hard Whether to update .htaccess (hard flush)
// or just update rewrite_rules transient (soft flush). Default is true (hard).
function flush_rewrite_rules( $hard = true ) {
	global $ws_rewrite;
	$ws_rewrite->flush_rules( $hard );
}

// Updates the htaccess file with the current rules if it is writable.
// Always writes to the file if it exists and is writable to ensure that we blank out old rules.
// @since 0.0.1
// @global WS_Rewrite $ws_rewrite
function save_mod_rewrite_rules() {
	if ( is_multisite() )
		return;

	global $ws_rewrite;

	$home_path = get_home_path();
	$htaccess_file = $home_path.'.htaccess';

	// If the file doesn't already exist check for write access to the directory
	// and whether we have some rules. Else check for write access to the file.
	if ((!file_exists($htaccess_file) && is_writable($home_path) && $ws_rewrite->using_mod_rewrite_permalinks()) || is_writable($htaccess_file)) {
		if ( got_mod_rewrite() ) {
			$rules = explode( "\n", $ws_rewrite->mod_rewrite_rules() );
			return insert_with_markers( $htaccess_file, 'WordPress', $rules );
		}
	}

	return false;
}

// Updates the IIS web.config file with the current rules if it is writable.
// If the permalinks do not require rewrite rules then the rules are deleted from the web.config file.
// @since 0.0.1
// @global WS_Rewrite $ws_rewrite
// @return bool True if web.config was updated successfully
function iis7_save_url_rewrite_rules(){
	if ( is_multisite() )
		return;

	global $ws_rewrite;

	$home_path = get_home_path();
	$web_config_file = $home_path . 'web.config';

	// Using win_is_writable() instead of is_writable() because of a bug in Windows PHP
	if ( iis7_supports_permalinks() && ( ( ! file_exists($web_config_file) && win_is_writable($home_path) && $ws_rewrite->using_mod_rewrite_permalinks() ) || win_is_writable($web_config_file) ) ) {
		$rule = $ws_rewrite->iis7_url_rewrite_rules(false, '', '');
		if ( ! empty($rule) ) {
			return iis7_add_rewrite_rule($web_config_file, $rule);
		} else {
			return iis7_delete_rewrite_rule($web_config_file);
		}
	}
	return false;
}

// Rewrite API: WS_Rewrite class
// @package WS
// @subpackage Rewrite
// @since 0.0.1
// Core class used to implement a rewrite component API.
// The WS_Rewrite class writes the rewrite module rules to the .htaccess file.
// It also handles parsing the request to get the correct setup for the WS Query class.
// The Rewrite along with WS class function as a front controller for WS.
// You can add rules to trigger your page view and processing using this
// component. The full functionality of a front controller does not exist,
// meaning you can't define how the template files load based on the rewrite rules.
// @since 0.0.1
class WS_Rewrite {
	// Rewrite rules to match against the request to find the redirect or query.
	// @since0.0.1
	// @var array
	var $rules;

	// Additional rules added external to the rewrite class.
	// Those not generated by the class, see add_rewrite_rule().
	// @since 0.0.1
	// @var array
	var $extra_rules = array();

	// Additional rules that belong at the beginning to match first.
	// Those not generated by the class, see add_rewrite_rule().
	// @since 0.0.1
	// @var array
	var $extra_rules_top = array();

	// Rules that don't redirect to WordPress' index.php.
	// These rules are written to the mod_rewrite portion of the .htaccess,
	// and are added by add_external_rule().
	// @since 0.0.1
	// @var array
	var $non_ws_rules = array();

	// Extra permalink structures, e.g. categories, added by add_permastruct().
	// @since 2.1.0
	// @var array
	var $extra_permastructs = array();

	// Endpoints (like /trackback/) added by add_rewrite_endpoint().
	// @since 0.0.1
	// @var array
	var $endpoints;

	// Adds a rewrite rule that transforms a URL structure to a set of query vars.
	// Any value in the $after parameter that isn't 'bottom' will result in the rule
	// being placed at the top of the rewrite rules.
	// @since 0.0.1
	// @param string       $regex Regular expression to match request against.
	// @param string|array $query The corresponding query vars for this rewrite rule.
	// @param string       $after Optional. Priority of the new rule. Accepts 'top'
	//                            or 'bottom'. Default 'bottom'.
	public function add_rule( $regex, $query, $after = 'bottom' ) {
		if ( is_array( $query ) ) {
			$external = false;
			$query = add_query_arg( $query, 'index.php' );
		} else {
			$index = false === strpos( $query, '?' ) ? strlen( $query ) : strpos( $query, '?' );
			$front = substr( $query, 0, $index );

			$external = $front != $this->index;
		}

		// "external" = it doesn't correspond to index.php.
		if ( $external ) {
			$this->add_external_rule( $regex, $query );
		} else {
			if ( 'bottom' == $after ) {
				$this->extra_rules = array_merge( $this->extra_rules, array( $regex => $query ) );
			} else {
				$this->extra_rules_top = array_merge( $this->extra_rules_top, array( $regex => $query ) );
			}
		}
	}
	// Adds an endpoint, like /trackback/.
	// @since 0.0.1
	// @see add_rewrite_endpoint() for full documentation.
	// @global WP $ws
	// @param string      $name      Name of the endpoint.
	// @param int         $places    Endpoint mask describing the places the endpoint should be added.
	// @param string|bool $query_var Optional. Name of the corresponding query variable. Pass `false` to
	//                               skip registering a query_var for this endpoint. Defaults to the value of `$name`.
	public function add_endpoint( $name, $places, $query_var = true ) {
		global $ws;

		// For backward compatibility, if null has explicitly been passed as `$query_var`, assume `true`.
		if ( true === $query_var || null === func_get_arg( 2 ) ) {
			$query_var = $name;
		}
		$this->endpoints[] = array( $places, $name, $query_var );

		if ( $query_var ) {
			$ws->add_query_var( $query_var );
		}
	}

	// Retrieves the rewrite rules.
	// The difference between this method and WS_Rewrite::rewrite_rules() is that
	// this method stores the rewrite rules in the 'rewrite_rules' option and retrieves
	// it. This prevents having to process all of the permalinks to get the rewrite rules
	// in the form of caching.
	// @since 0.0.1
	// @return array Rewrite rules.
	public function ws_rewrite_rules() {
		$this->rules = get_option('rewrite_rules');
		if ( empty($this->rules) ) {
			$this->matches = 'matches';
			$this->rewrite_rules();
			if ( ! did_action( 'ws_loaded' ) ) {
				add_action( 'ws_loaded', array( $this, 'flush_rules' ) );
				return $this->rules;
			}
			update_option('rewrite_rules', $this->rules);
		}

		return $this->rules;
	}

	// Removes rewrite rules and then recreate rewrite rules.
	// Calls WS_Rewrite::ws_rewrite_rules() after removing the 'rewrite_rules' option.
	// If the function named 'save_mod_rewrite_rules' exists, it will be called.
	// @since 0.0.1
	// @staticvar bool $do_hard_later
	// @param bool $hard Whether to update .htaccess (hard flush) or just update rewrite_rules option (soft flush). Default is true (hard).
	public function flush_rules( $hard = true ) {
		static $do_hard_later = null;

		// Prevent this action from running before everyone has registered their rewrites.
		if ( ! did_action( 'ws_loaded' ) ) {
			add_action( 'ws_loaded', array( $this, 'flush_rules' ) );
			$do_hard_later = ( isset( $do_hard_later ) ) ? $do_hard_later || $hard : $hard;
			return;
		}

		if ( isset( $do_hard_later ) ) {
			$hard = $do_hard_later;
			unset( $do_hard_later );
		}

		update_option( 'rewrite_rules', '' );
		$this->ws_rewrite_rules();

		// Filters whether a "hard" rewrite rule flush should be performed when requested.
		// A "hard" flush updates .htaccess (Apache) or web.config (IIS).
		// @since 3.7.0
		// @param bool $hard Whether to flush rewrite rules "hard". Default true.
		if ( ! $hard || ! apply_filters( 'flush_rewrite_rules_hard', true ) ) {
			return;
		}
		if ( function_exists( 'save_mod_rewrite_rules' ) )
			save_mod_rewrite_rules();
		if ( function_exists( 'iis7_save_url_rewrite_rules' ) )
			iis7_save_url_rewrite_rules();
	}
}
